### PR TITLE
Merging the changes of the last few weeks into the open repository

### PR DESCRIPTION
**Pull request by andyspiros**
After this PR we could tag 0.1.

### CODE REVIEW

**Comment by cosunae** [comment]
If we start doing releases we will need a ReleaseNotes.txt

**Comment by andyspiros** [comment]
You are right, maybe we can call it `Changelog.txt`, which is more common, I think. For the first version I will add some point concerning this specific merge, i.e. the merges we had.

**Comment by cosunae** [comment]
sounds good

**Comment by andyspiros** [comment]
I just updated the gitignore file. It contained some cmake stuff which should go in the build directory instead. Feel free to update it for cases I did not consider.

**Comment by andyspiros** [comment]
I tried to be complete, but please, @cosunae , @clementval , @pspoerri have a look at it and complete it if needed.

I did it in markdown style, but I'm not sure this is the best way, since Github does not render it anyway. Maybe we can call it `ChangeLog.md`. In facts, open source project tend to name it just `ChangeLog` and there is some kind of syntax for it. Don't know what is best.

**Comment by pspoerri** [comment]
lgtm.

**Comment by cosunae** [comment]
just a question about the release number. Wont we need x.x.x convention?
last - minor changes, bug fixes
medium - some new functionality, implementation
first - breaks backward compatibility. 

How about 1.0.0 or 1.1.1 or 0.0.1 or 0.0.0?

**Comment by andyspiros** [comment]
I still propose 0.1, meaning 0.1.0. I think we are heading to 1.0, and this is a large step in that direction, though we need a few more (e.g. 4-5) of such steps. This is definitely not a bugfix release. In case we fix some bugs and want to come out with a new release we can do 0.1.1 and so on (a lot of projects work this way, e.g. Linux, KDE).

**Comment by cosunae** [comment]
alright

**Pull request merged**
